<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    <AssemblyVersion>2.0.1</AssemblyVersion>
    <FileVersion>2.0.1</FileVersion>
    <Version>2.0.1</Version>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWindowsForms>true</UseWindowsForms>
		<!-- â† TO MUSI BYÄ†! -->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TTD.Core\TTD.Core.csproj" />
		<ProjectReference Include="..\TTD.Data\TTD.Data.csproj" />
	</ItemGroup>

</Project>









