// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTD.Data;

#nullable disable

namespace TTD.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826095101_AddTrackAndPlatformSystem")]
    partial class AddTrackAndPlatformSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TTD.Data.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("TTD.Data.Models.RouteStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DistanceFromPrevious")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StopDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StopOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("StopOrder")
                        .HasDatabaseName("IX_RouteStation_StopOrder");

                    b.HasIndex("RouteId", "StationId", "StopOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_RouteStation_Unique");

                    b.ToTable("RouteStations");
                });

            modelBuilder.Entity("TTD.Data.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrainId")
                        .HasDatabaseName("IX_Schedule_TrainId");

                    b.HasIndex("RouteId", "DepartureTime")
                        .IsUnique()
                        .HasDatabaseName("IX_Schedule_Route_Departure");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("TTD.Data.Models.ScheduleTravelTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RouteStationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TravelTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RouteStationId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ScheduleTravelTimes");
                });

            modelBuilder.Entity("TTD.Data.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCargo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPassenger")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("MapX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MapY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2);

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("TTD.Data.Models.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsElectric")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TractiveEffort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("TTD.Data.Models.RouteStation", b =>
                {
                    b.HasOne("TTD.Data.Models.Route", "Route")
                        .WithMany("RouteStations")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTD.Data.Models.Station", "Station")
                        .WithMany("RouteStations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("TTD.Data.Models.Schedule", b =>
                {
                    b.HasOne("TTD.Data.Models.Route", "Route")
                        .WithMany("Schedules")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTD.Data.Models.Train", "Train")
                        .WithMany("Schedules")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TTD.Data.Models.ScheduleTravelTime", b =>
                {
                    b.HasOne("TTD.Data.Models.RouteStation", "RouteStation")
                        .WithMany("ScheduleTravelTimes")
                        .HasForeignKey("RouteStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTD.Data.Models.Schedule", "Schedule")
                        .WithMany("TravelTimes")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteStation");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("TTD.Data.Models.Route", b =>
                {
                    b.Navigation("RouteStations");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TTD.Data.Models.RouteStation", b =>
                {
                    b.Navigation("ScheduleTravelTimes");
                });

            modelBuilder.Entity("TTD.Data.Models.Schedule", b =>
                {
                    b.Navigation("TravelTimes");
                });

            modelBuilder.Entity("TTD.Data.Models.Station", b =>
                {
                    b.Navigation("RouteStations");
                });

            modelBuilder.Entity("TTD.Data.Models.Train", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
